---
# =================================================================
# PART 1: COMMON TASKS (EXECUTED ON ALL K8S NODES)
# =================================================================
- name: Nginx and Certbot setup
  hosts: control_plane
  become: true
  gather_facts: false
  tags: nginx_all
  roles:
    - role: k8s_nginx
