installation:
  enabled: true
  kubernetesProvider: ""
  calicoNetwork:
    mtu: 1450
    ipPools:
      - cidr: 10.244.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
