---
- name: Install Nginx
  block:
    - name: Nginx vHosts for basic services
      ansible.builtin.template:
        src: nginx.tpl
        dest: /etc/nginx/sites-enabled/{{ item.service_name }}.conf
        owner: root
        group: root
        mode: "0644"
      loop: "{{ target_services }}"
      notify: Reload Nginx

    - name: Create SSL certificates with Certbot for Nginx
      ansible.builtin.shell: |
        certbot --nginx -n --agree-tos --email admin@{{ ext_domain }} -d {{ item.service_name }}.{{ ext_domain }} --redirect
      loop: "{{ target_services }}"
      args:
        creates: "/etc/letsencrypt/live/{{ item.service_name }}.{{ ext_domain }}/fullchain.pem"
      notify: Reload Nginx
