---
- name: Deploy KeyCloak
  block:
    - name: Create random KeyCloak password
      ansible.builtin.set_fact:
        keycloak_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

    - name: KeyCloak get manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/refs/heads/main/kubernetes/keycloak.yaml
        dest: ./keycloak.yaml

    - name: KeyCloak patch root password
      ansible.builtin.replace:
        path: ./keycloak.yaml
        regexp: '(KC_BOOTSTRAP_ADMIN_PASSWORD\s+value:)\s*".*"'
        replace: '\1 "{{ keycloak_password }}"'

    - name: Install KeyCloak to cluster
      ansible.builtin.shell: |
        kubectl create ns auth && kubectl -n auth apply -f ./keycloak.yaml
        rm -f ./keycloak.yaml
      notify:
        - Restart systemd-resolved

    - meta: flush_handlers

    - name: Copy set-keycloak.sh script to control plane node
      ansible.builtin.copy:
        src: set-keycloak.sh
        dest: /home/ubuntu/set-keycloak.sh
        mode: "0777"

    - name: Wait until KeyCloak starts
      ansible.builtin.shell: |
        kubectl debug -it -n auth keycloak-0 --profile=general --image nginx -- /bin/bash -c 'until curl -s localhost:9000/health | grep UP; do echo wait for master up; sleep 5; done'

    - name: Update KeyCloak client secret for admin-cli
      become: false
      ansible.builtin.shell: |
        bash /home/ubuntu/set-keycloak.sh -u admin -p {{ keycloak_password }} -k http://keycloak.auth.svc.cluster.local:8080
      register: keycloak_client_secret

    - name: Save KeyCloak password to file
      delegate_to: localhost
      become: false
      ansible.builtin.lineinfile:
        path: password_keycloak.txt
        create: yes
        line: "{{ keycloak_password }}"

    - name: Save KeyCloak client secret to file
      delegate_to: localhost
      become: false
      ansible.builtin.lineinfile:
        path: password_keycloak_secret.txt
        create: yes
        line: "{{ keycloak_client_secret.stdout }}"
