---
- name: Setup KeyCloak
  include_tasks:
    file: keycloak.yml

- name: Setup Vault
  include_tasks:
    file: vault.yml

- meta: flush_handlers

- name: Setup Basic Nginx services
  include_role:
    name: k8s_nginx
  vars:
    target_services: "{{ nginx_services | selectattr('type', 'equalto', 'basic') | list }}"
