---
- name: Deploy KeyCloak
  block:
    - name: Create random KeyCloak password
      ansible.builtin.set_fact:
        keycloak_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

    - name: Fetch keycloak manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/refs/heads/main/kubernetes/keycloak.yaml
        dest: ./keycloak.yaml

    - name: Modify keycloak manifest for new password
      ansible.builtin.replace:
        path: ./keycloak.yaml
        regexp: '(KC_BOOTSTRAP_ADMIN_PASSWORD\s+value:)\s*".*"'
        replace: '\1 "{{ keycloak_password }}"'

    - name: Apply keycloak manifest
      ansible.builtin.shell: |
        kubectl create ns auth && kubectl -n auth apply -f ./keycloak.yaml
        rm -f ./keycloak.yaml

    - name: Save KeyCloak password to file
      delegate_to: localhost
      become: false
      ansible.builtin.lineinfile:
        path: keycloak_password.txt
        create: yes
        line: "{{ keycloak_password }}"

- name: Deploy Vault
  block:
    - name: Create random Vault password
      ansible.builtin.set_fact:
        vault_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

    - name: Install Vault with Helm
      ansible.builtin.shell: |
        helm repo add hashicorp https://helm.releases.hashicorp.com
        helm repo update
        curl https://raw.githubusercontent.com/hashicorp/vault-helm/refs/heads/main/values.yaml > /home/ubuntu/vault.yaml

    - name: Vault patch PVC claim size
      ansible.builtin.replace:
        path: /home/ubuntu/vault.yaml
        regexp: "10Gi"
        replace: "128Mi"

    - name: Vault patch dev mode
      ansible.builtin.replace:
        path: /home/ubuntu/vault.yaml
        regexp: '^\s+dev:\n\s+enabled: false'
        replace: "  dev:\n    enabled: true"

    - name: Vault patch root password
      ansible.builtin.replace:
        path: /home/ubuntu/vault.yaml
        regexp: 'devRootToken: "root"'
        replace: 'devRootToken: "{{ vault_password }}"'

    - name: Apply vault manifest
      ansible.builtin.shell: |
        kubectl create ns vault
        helm -n vault install vault hashicorp/vault -f /home/ubuntu/vault.yaml
        rm -f /home/ubuntu/vault.yaml

    - name: Save Vault password to file
      delegate_to: localhost
      become: false
      ansible.builtin.lineinfile:
        path: vault_password.txt
        create: yes
        line: "{{ vault_password }}"

- name: Setup Basic Nginx services
  include_role:
    name: k8s_nginx
  vars:
    target_services: "{{ nginx_services | selectattr('type', 'equalto', 'basic') | list }}"
