---
- name: Install Flanel CNI (Container Network Interface)
  ansible.builtin.shell: |
    {{ kubectl_command }} {{ flannel_url }}
  when: use_flannel and not use_calico

- name: Install Calico CNI (Container Network Interface)
  block:
    - name: Copy Calico manifest to control plane node
      ansible.builtin.copy:
        src: ../files/calico-tigera.yaml
        dest: /tmp/calico-tigera.yaml

    - name: Install Calico CNI (Container Network Interface)
      ansible.builtin.shell: |
        helm repo add projectcalico https://docs.tigera.io/calico/charts
        helm repo update
        helm install calico projectcalico/tigera-operator --version {{ calico_version }} -f /tmp/calico-tigera.yaml --namespace tigera-operator --create-namespace
  when: use_calico and not use_flannel

- name: Install Traefik CRDs
  ansible.builtin.shell: |
    {{ kubectl_command }} {{ item }}
  when: use_traefik
  with_items: "{{ traefik_urls }}"

- name: Install Cert-Manager CRDs
  ansible.builtin.shell: |
    {{ kubectl_command }} {{ cert_manager_crds_url }}
  when: use_cert_manager

# Install MetalLB CRDs. Without these, LoadBalancer services won't work and
# you won't be able to expose your applications properly.
- name: Install MetalLB CRDs
  ansible.builtin.shell: |
    {{ kubectl_command }} {{ item }}
  when: use_metallb
  with_items: "{{ metallb_urls }}"

- name: Install Basic CRDs for ArgoCD
  ansible.builtin.shell: |
    {{ kubectl_command }} {{ item }}
  when: use_argocd
  with_items: "{{ argocd_urls }}"

- name: Install Local Path Storage and set it as default
  ansible.builtin.shell: |
    mkdir -p /opt/local-path-provisioner
    chmod 777 /opt/local-path-provisioner
    {{ kubectl_command }} {{ local_path_storage_manifest_url }}
    kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  when: use_local_path_storage
