---
- name: Control Plane
  block:
    - name: Get Private IP Address (from VPC)
      set_fact:
        private_ip: "{{ ansible_facts['default_ipv4']['address'] }}"

    - name: Create rc.local directory
      ansible.builtin.file:
        path: /etc/rc.local
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create IP update script
      ansible.builtin.copy:
        content: |
          DNS={{ cp_dns_name }}
          PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
          PWD={{ he_net_password }}
          curl "https://dyn.dns.he.net/nic/update?hostname=${DNS}&password=${PWD}&myip=${PUBLIC_IP}"
          echo "{\"status\": \"updated\", \"timestamp\": \"$(date)\", \"ip\": \"${PUBLIC_IP}\"}"
        dest: /etc/rc.local/ip.sh
        owner: root
        group: root
        mode: "0700"

    - name: Update crontab
      ansible.builtin.blockinfile:
        path: /etc/crontab
        content: |
          # Custom cron jobs
          # */10 *  * * *   root    test -x /etc/rc.local/ip.sh || /etc/rc.local/ip.sh >> /var/log/ip_update.log
          @reboot /etc/rc.local/ip.sh
          @daily certbot renew
          #
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: EOF

    - name: Set up external IP
      ansible.builtin.shell: |
        /etc/rc.local/ip.sh

    - name: Kubeadm Init (Control Plane setup)
      ansible.builtin.command: >
        kubeadm init 
        --pod-network-cidr={{ pod_cidr }} 
        --apiserver-advertise-address={{ private_ip }}
        --ignore-preflight-errors=Swap,NumCPU,Mem
        {% if cp_dns_name %}
        --apiserver-cert-extra-sans={{ cp_dns_name }}
        {% endif %}
        {% if groups['control_plane'] | length > 1 %}
        --control-plane-endpoint={{ cp_dns_name }}:6443
        {% endif %}
      register: kubeadm_init_result
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Set up kubectl configuration for user
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        rm -fr $HOME/.kube/config
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $USER:$USER $HOME/.kube/ -R
        mkdir -p /home/ubuntu/.kube
        rm -fr /home/ubuntu/.kube/config
        sudo cp -i /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
        sudo chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/ -R

    - name: Replace API server IP with DNS name in user's kubeconfig
      ansible.builtin.replace:
        path: /home/{{ ansible_user }}/.kube/config
        regexp: "server: https://{{ private_ip }}:6443"
        replace: "server: https://{{ cp_dns_name }}:6443"
        backup: yes

    - name: Fetch the final kubeconfig to local working directory
      ansible.builtin.fetch:
        src: /home/{{ ansible_user }}/.kube/config
        dest: "{{ lookup('env','HOME') }}/.kube/config"
        flat: yes

    - name: Install basic deployments
      include_tasks: install_basic_deployments.yml
