---
- name: Restart Kubelet
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: true
    state: restarted

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
